name: app_ui
description: app ui
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3
  intl: ^0.18.0

dev_dependencies:
  very_good_analysis: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit-Regular.ttf
          weight: 400
        - asset: assets/fonts/Outfit-Bold.ttf
          weight: 700
    - family: PaytoneOne
      fonts:
        - asset: assets/fonts/PaytoneOne-Regular.ttf
          weight: 400
