name: api
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  broadcast_bloc: ^0.1.0-dev.2
  dart_frog: ^1.0.0
  dart_frog_web_socket: ^1.0.0
  domain:
    path: ../domain

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^5.0.0
